import turtle

bgmi = turtle.Turtle()
turtle.bgcolor("black")
bgmi.color("orange")
#bgmi.speed(0)

def rect(): # length 340 # breadh 182
    bgmi.pensize(9)
    bgmi.forward(170)
    bgmi.left(45)
    bgmi.forward(6)
    bgmi.left(45)
    bgmi.forward(170)
    bgmi.left(45)
    bgmi.forward(6)
    bgmi.left(45)
    bgmi.forward(330)
    bgmi.left(45)
    bgmi.forward(6)
    bgmi.left(45)
    bgmi.forward(170)
    bgmi.left(45)
    bgmi.forward(6)
    bgmi.left(45)
    bgmi.forward(170)

def four_corner_lines():
    bgmi.pensize(12)
    bgmi.penup()
    bgmi.forward(180)
    bgmi.left(90)
    bgmi.forward(35)
    bgmi.left(90)
    bgmi.pendown()
    bgmi.forward(12)
    bgmi.penup()
    bgmi.forward(344)
    bgmi.pendown()
    bgmi.forward(17)
    bgmi.penup()
    bgmi.right(90)
    bgmi.forward(105)
    bgmi.right(90)
    bgmi.pendown()
    bgmi.forward(17)
    bgmi.penup()
    bgmi.forward(344)
    bgmi.pendown()
    bgmi.forward(12)

def b(): #draw  b alphabet 
    bgmi.penup()
    bgmi.left(180)
    bgmi.forward(280)
    bgmi.pendown()
    bgmi.forward(40)
    bgmi.left(90)
    bgmi.forward(100)
    bgmi.left(180)
    bgmi.forward(52)
    bgmi.right(90)
    bgmi.forward(40)
    bgmi.left(90)
    bgmi.forward(47)

def g():#draw g alphabet
    bgmi.penup()
    bgmi.right(90)
    bgmi.forward(32)
    bgmi.right(90)
    bgmi.pendown()
    bgmi.forward(98)
    bgmi.left(90)
    bgmi.forward(40)
    bgmi.left(90)
    bgmi.forward(98)

def m(): #draw m alphabet
    bgmi.penup()
    bgmi.right(90)
    bgmi.forward(35)
    bgmi.pendown()
    bgmi.forward(45)
    bgmi.right(90)
    bgmi.forward(43)
    bgmi.right(45)
    bgmi.forward(5)
    bgmi.right(45)
    bgmi.forward(40)
    bgmi.left(90)
    bgmi.forward(5)
    bgmi.left(90)
    bgmi.forward(40)
    bgmi.right(45)
    bgmi.forward(5)
    bgmi.right(45)
    bgmi.forward(40)
    bgmi.right(90)
    bgmi.forward(45)
    bgmi.right(90)
    bgmi.forward(96)

def i():#draw i 
    bgmi.penup()
    bgmi.right(180)
    bgmi.forward(53)
    bgmi.left(90)
    bgmi.forward(98)
    bgmi.pendown()
    bgmi.forward(25)
    bgmi.right(90)
    bgmi.forward(45)
    bgmi.right(90)
    bgmi.forward(45)
    bgmi.right(90)
    bgmi.forward(95)
    bgmi.right(90)
    bgmi.forward(40)    

# calling all functions
rect()
four_corner_lines()
b()
g()
m()
i()

turtle.done()